apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::090941724528:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1Q973J8IXEGSC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::090941724528:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-10T07:47:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "217197"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 872ef43e-f3e8-4f61-aa21-95eda392be01
